### PR TITLE
Add support for setting indicator color

### PR DESCRIPTION
**Pull request by almarklein**
* [x] Add `color` arg, eg  `VolumeSlicer(... color='red')`.
* [x] Draw a rectangle around the image in that color. (But only when other slicers are present.)
* [x] Other slicers draw indicators in that color.
* [x] Indicators are now across the image.
* [x] Decide on way to display the color of the current slicer. -> corners with slightly thicker lines.
* [x] What should the default color be -> different color for each axis based on a good colormap (e.g. D3).
* [x] Refactor to use one store less (combine "index" and "pos" into "state).
* [x] Also include (rate limited) axis ranges, so that the indicators can be drawn correctly when zoomed in.
* [x] Renamed some fields in the `info` store to avoid confusion with shape, sampling and origin.
* [x] Slicer colors are taken from a plotly colormap.
* [x] The `create_overlay_data()` method samples default colors from the same colormap. 
* [x] If a colormap is given to `create_overlay_data()`, the first element is used where mask is 1 (was 0).
* [x] Update slicer_with_3_views to show slicer view ranges in the 3D figure.
* [x] Find actual figure size via `gd._fullLayout.width` / `height`?
----

afbeelding

### CODE REVIEW

**Comment by almarklein** [comment]
> Hmm the border is a bit intense... 

Yeah, I played a bit with slimmer lines, but certain colors would be barely visible then. I'll try the corners-thing.

**Comment by emmanuelle** [comment]
Maybe a matter of color and taste, but I'm fine with lines as they are now. And it helps a lot with the navigation, love this feature!!

**Comment by emmanuelle** [comment]
What do you think @surchs? Are lines too thick or ok? We need more opinions :-).

**Comment by almarklein** [comment]
Added another possible approach to the top post.

**Comment by surchs** [comment]
Nice, this looks very cool and makes it easier to use! 
I like the lines as well with the current thickness. Maybe to denote the individual axis graphs, we could just use a thick line on the bottom, rather than a complete border. And maybe this "indicator" line should be optional and default to hidden when no slicer colour is defined (or they all default to turquoise).

**Comment by nicolaskruchten** [comment]
I think this is looking pretty great! The corner indicators could be a little smaller perhaps, and I personally preferred the "outer tick" style of indicators for the other two, that way they don't occlude the figure, but that's maybe just a personal style thing.

It would be awesome to get these indicators somehow reflected in the 3d view as well if possible in the example with the 3d plot :)

**Comment by almarklein** [comment]
@nicolaskruchten 
afbeelding

**Comment by nicolaskruchten** [comment]
zomg that's cool

**Comment by almarklein** [comment]
Ready for review.

The corner-indicators are now actually square, and have the same size in each view targeting the same volume.

Quite a few changes, I also renamed some variables, and refactored a bit.

**Comment by almarklein** [comment]
Hold on - After discussion with @nicolaskruchten I'm going to try changing how we define the "indicator ranges".

**Pull request merged**
